package com.example.demo.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.Email;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Size;

import com.sun.istack.NotNull;

//User class represents an entity that can be persisted in a database table.
// It contains fields representing the columns in the table, along with annotations and constraints to
// define the mapping and validation rules

//The class has several fields that represent the columns in the "users" table.
@Entity
@Table(name="users")//This annotation is used to specify the name of the database table that corresponds to the entity.
public class User {

	@Id//@Id annotation: This annotation is used to specify the primary key of the entity.
	@GeneratedValue(strategy= GenerationType.AUTO)//@GeneratedValue annotation: This annotation is used to specify the strategy for generating the values of the primary key. Here primary key values will be automatically generated by the underlying database system.
	private long uid;
	
	@NotNull
	@Size(min = 2 , message="First Name should have atelast 2 characters")//@Size constraints, specifying that the field cannot be null and must have a minimum size of 2 characters.
	@Column(name="first_name")//Represents the "first_name" column in the table.
	private String firstName;
	
	@NotNull
	@Column(name="mobile")
	private Long mobile;
	
	@NotNull
	@Size(min = 2 , message="Last Name should have atelast 2 characters")
	@Column(name="last_name")
	private String lastName;
	
	@NotBlank
	@Email//@Email constraints, specifying that the field cannot be blank and must be a valid email address.
	@Column(name="email")
	private String email;
	
	@Column(name="address1")
	private String address1;
	
	@Column(name="address2")
	private String address2;

	public User() {}
	public User(String firstName, String lastName, String email, String address1, String address2,long mobile) {
		super();
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.address1 = address1;
		this.address2 = address2;
		this.mobile=mobile;
	}

	public Long getMobile() {
		return mobile;
	}

	public void setMobile(Long mobile) {
		this.mobile = mobile;
	}

	public long getUid() {
		return uid;
	}

	public void setUid(long uid) {
		this.uid = uid;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAddress1() {
		return address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	public String getAddress2() {
		return address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

}
